accounts/urls.py
from django.urls import path
from . import views
app_name ="accounts"

urlpatterns = [
    path("register/" , views.register, name="register"),
    path("login/", views.login_user, name= "login"),
    path("logout/" , views.logout_user, name= "logout")
]

main/urls.py
#this is our main app , we create apps in our website which are of two types one is main app(i.e this) and one is accounts app

# from django.urls import path
# from . import views
# app_name ="main"

from django.urls import path
from . import views
app_name ="main"

urlpatterns = [
    path('',views.home, name="home"), #here blank sapce in first ' ' because it is supposed to be our home page. there is nothing before to be written before the url of our home page
    path('details/<int:id>/' , views.detail, name="detail"),
    path('search/' , views.searchresults, name="searchresults"),
    path('review/', views.review, name='review'),
    path('genre/<int:genreid>/' , views.genre, name="genre"),
    # path('addreview/<int:id>/' ,views.add_review, name= "add_review")
]






# urlpatterns = [
#     path('',views.home, name="home"), #here blank sapce in first ' ' because it is supposed to be our home page. there is nothing before to be written before the url of our home page
#     path('details/<int:id>/' , views.detail, name="detail"),
#     path('addmovies/' , views.add_movies , name="add_movies"),
#     path('editmovies/<int:id>/' , views.edit_movies , name= "edit_movies"),
#     path('deletemovies/<int:id>/' , views.delete_movies,  name= "delete_movies")
# ]

movie_review/urls.py
from django.contrib import admin
from django.urls import path, include #assume some libraries of django named as path and include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')), #this command is gonna include the urls.py file from our main app
    path('accounts/', include('accounts.urls'))
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Movie(models.Model): # we are creating a table named Movie
    #fields for the Movie table
    name = models.CharField(max_length=350)
    director= models.CharField(max_length=350)
    cast= models.CharField(max_length=1000)
    description= models.TextField(max_length=5000)
    release_date= models.DateField()
    averageRating = models.FloatField(default=0)
    image = models.URLField(default=None, null=True)


    def __str__(self): #function called string returns whatever you want in the string version in django-admin
        return self.name

    def __unicode__(self):
        return self.name

        #now after creating a table we need to register it to admin.py
        #and after making any changes to database we need to run migrations
class reviews(models.Model):
    movieid = models.IntegerField()
    user= models.CharField(max_length=100)
    review = models.TextField(max_length=3000)
    rating = models.FloatField(default=0)

main/forms.py
from django import forms
from .models import *

# movie add form
class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('name' , 'director' , 'cast' , 'description' , 'release_date' , 'image' )

class ReviewForm(forms.ModelForm):
    class Meta:
        model= reviews
        fields= {'review', 'rating', 'movieid', 'user'}

main/views.py
#logic of our code goes here
#any pages you wanna create goes here
from unicodedata import name
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import *
from .forms import *
import json
from urllib import response
import requests
#function based views
#home page
apiBaseURL = 'https://api.themoviedb.org/3/'
apiKey = '3d9b4ef8cf0ea93474001f18dabe2e00'

imagebase = 'https://image.tmdb.org/t/p/w300'

#home page
def home(request): #what the users will see on our front page every view that has to be viewed i the html has to go thru request parameter
    # allMovies= Movie.objects.all() # select * from Movie (equivalent SQL query)
    # # we need to create a dictionary for our html template. Html file will contain "movies" which will refer to allMovies
    # context = {
    #     "movies" : allMovies,
    # }
    response = requests.get(apiBaseURL + 'movie/now_playing?api_key=' + apiKey).json()
    popular_movies = response["results"]
    movie_id = []
    for i in popular_movies:
        movie_id.append(i["id"])
    response3 = {}
    for i in movie_id:
        response3[i] = requests.get(apiBaseURL + 'movie/' + str(i) + '?api_key=' + apiKey).json()
    return render(request, 'main/index.html', {'response3' : response3})

#detail page
def detail(request,id):
    # movie= Movie.objects.get(id=id) #select * from Moview where id=id
    # context = {
    #     "movie" : movie
    # }
    review = reviews.objects.all().filter(movieid = id)
    response = requests.get(apiBaseURL + 'movie/' + str(id) + '?api_key=' + apiKey).json()
    title = response["title"]
    overview = response["overview"]
    rating = response["vote_average"]
    release = response["release_date"]
    imageurl = imagebase + response["poster_path"]
    if Movie.objects.filter(name=title).exists():
        pass
    else:
        moviedata = Movie(name=title, description=overview, averageRating=rating, release_date=release, image=imageurl)
        moviedata.save()
    # review = reviews.objects.all().filter(movieid = movie_id)
    review = reviews.objects.all().filter(movieid = id)
    return render(request, 'main/details.html', {'response':response, 'review':review})

#search a movie

def searchresults(request):
    searchTerm = request.POST.get("searchTerm")
    response = requests.get(apiBaseURL + 'search/movie?api_key=' + apiKey + '&language=en-US&page=1&include_adult=false&query=' + searchTerm).json()
    popular_movies = response["results"]
    movie_id = []
    for i in popular_movies:
        movie_id.append(i["id"])
    response3 = {}
    for i in movie_id:
        response3[i] = requests.get(apiBaseURL + 'movie/' + str(i) + '?api_key=' + apiKey).json()
    return render(request, 'main/search.html/', {'response3' : response3, 'searchTerm':searchTerm})

def review(request):
    id = request.POST.get("movieid")

    if request.user.is_authenticated:
        response = requests.get(apiBaseURL + 'movie/' + str(id) + '?api_key=' + apiKey).json()

        if request.method== "POST":

            review = request.POST.get("review")
            rating = request.POST.get("rating")
            username = request.user.username
            data = reviews(movieid=id, user=username, review=review, rating=rating)
            review = reviews.objects.all().filter(movieid = id)
            x = False
            for i in range(0,len(review)):
                if review[i].user == username:
                    x = True
                    break
            if x:
                print("here")
                return render(request, 'main/details.html/', {'response':response, 'review':review})

            else:
                data.save()
                review = reviews.objects.all().filter(movieid = id)
                return render(request, 'main/details.html/', {'response':response, 'review':review})
        else:
            pass
        return render(request, 'main/details.html', {'response':response, 'review':review})
    else:
        return redirect("accounts:login")

def genre(request,genreid):

    response = requests.get(apiBaseURL + 'genre/' + str(genreid) + '/movies?api_key=' + apiKey + '&language=en-US&include_adult=false&sort_by=created_at.asc').json()
    popular_movies = response["results"]
    movie_id = []
    for i in popular_movies:
        movie_id.append(i["id"])
    response3 = {}
    for i in movie_id:
        response3[i] = requests.get(apiBaseURL + 'movie/' + str(i) + '?api_key=' + apiKey).json()
    return render(request, 'main/genre.html/', {'response3' : response3})











































































# def detail(request,id):
#     movie= Movie.objects.get(id=id) #select * from Moview where id=id
#     context = {
#         "movie" : movie
#     }
#
#     return render(request, 'main/details.html', context)
#
# #add movies to the databse
#
# def add_movies(request):
#     if request.user.is_authenticated:
#         if request.user.is_superuser:
#             if request.method == "POST":
#                 form = MovieForm(request.POST or None)
#
#                 #check if the form is valid
#                 if form.is_valid():
#                     data= form.save(commit=False)
#                     data.save()
#                     return redirect("main:home")
#
#             else:
#                 form =MovieForm()
#             return render( request, 'main/addMovies.html' , {"form" : form, "controller" : "Add movie"})
#
#         #if they are not admin
#         else:
#             return redirect("main:home")
#     #if they are not logged in
#     else:
#         return redirect("accounts:login")
#
#
# #edit movies details
# def edit_movies(request,id):
#     if request.user.is_authenticated:
#         if request.user.is_superuser:
#             movie= Movie.objects.get(id=id) #select * from Moview where id=id
#             if request.method == "POST":
#                 form = MovieForm(request.POST or None, instance=movie)
#
#                 if form.is_valid():
#                     data= form.save(commit=False)
#                     data.save()
#                     return redirect("main:detail" , id)
#                     # important point to note here after main: "<the name of the page that you gave in your urls.py>"
#
#             else:
#                 form = MovieForm(instance=movie)
#             return render(request , 'main/addMovies.html', {"form" : form, "controller" : "Edit Movie"})
#         #if they are not admin
#         else:
#             return redirect("main:home")
#     #if they are not logged in
#     else:
#         return redirect("accounts:login")
#
# def delete_movies(request,id):
#     if request.user.is_authenticated:
#         if request.user.is_superuser:
#             movie= Movie.objects.get(id=id)
#             movie.delete()
#             return redirect('main:home')
#         else:
#             return redirect("main:home")
#     #if they are not logged in
#     else:
#         return redirect("accounts:login")

main/templates/main/addmovies.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
  <div class="card">
    <div class="card-body">
      <h3 class="text-center"> {{ controller }} </h3>
      <form  action="" method="POST">
        {% csrf_token %}

        {{ form | crispy }}
        <input type="submit"  value="{{ controller }}" class="btn btn-danger">

      </form>

    </div>

  </div>

</div>


{% endblock %}

main/templates/main/base.html
<!doctype html>
<html lang="en">
 <head>
   <!-- Required meta tags -->
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

   <!-- Bootstrap CSS -->
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
   {% load static %}
   <link rel="stylesheet" href="{% static 'css/main.css' %}">
   <title>Filmster</title>

 </head>
 <body style=" background-image: url(https://wallpaperaccess.com/full/1155025.jpg);
 background-image: url(https://img.rawpixel.com/s3fs-private/rawpixel_images/website_content/tp238-background-03-kpqor301.jpg?w=800&dpr=1&fit=default&crop=default&q=65&vib=3&con=3&usm=15&bg=F4F4F3&ixlib=js-2.2.1&s=3431fda…);
 background-size: cover;
 background-position: center;

 background-image: url(https://www.xmple.com/wallpaper/black-pink-gradient-linear-3840x2160-c2-ff69b4-000000-a-105-f-14.svg);">
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
 <a class="navbar-brand" href="{% url 'main:home' %}">Filmster</a>
 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
   <span class="navbar-toggler-icon"></span>
 </button>

 <div class="collapse navbar-collapse" id="navbarSupportedContent">
   <ul class="navbar-nav mr-auto">
     <li class="nav-item active">
       <a class="nav-link" href="{% url 'main:home' %}">Home <span class="sr-only">(current)</span></a>
     </li>
     {% if user.is_authenticated %}
       <li class="nav-item dropdown">
       <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         {{user.username}}
       </a>
       <div class="dropdown-menu" aria-labelledby="navbarDropdown">
         <a class="dropdown-item" href="#">My Profile</a>
         <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
         <div class="dropdown-divider"></div>
           <a class="dropdown-item" href="#">Settings</a>
       </div>
      </li>
     {% else %}
     <li class="nav-item">
       <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
     </li>
     <li class="nav-item">
       <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
     </li>
     {% endif %}
     <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Genres</a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="/genre/28" action="/genre/">Action</a>
       <a class="dropdown-item" href="/genre/12" action="/genre/">Adventure</a>
       <a class="dropdown-item" href="/genre/16" action="/genre/">Animation</a>
       <a class="dropdown-item" href="/genre/35" action="/genre/">Comedy</a>
       <a class="dropdown-item" href="/genre/80" action="/genre/">Crime</a>
       <a class="dropdown-item" href="/genre/18" action="/genre/">Drama</a>
       <a class="dropdown-item" href="/genre/10751" action="/genre/">Family</a>
       <a class="dropdown-item" href="/genre/14" action="/genre/">Fantasy</a>
       <a class="dropdown-item" href="/genre/36" action="/genre/">History</a>
       <a class="dropdown-item" href="/genre/27" action="/genre/">Horror</a>
       <a class="dropdown-item" href="/genre/10402" action="/genre/">Music</option>
       <a class="dropdown-item" href="/genre/10749" action="/genre/">Romance</a>
       <a class="dropdown-item" href="/genre/878" action="/genre/">Science Fiction</a>
       <a class="dropdown-item" href="/genre/53" action="/genre/">Thriller</a>
     </div>
    </li>
  </ul>
   <form class="form-inline my-2 my-lg-0" method="post" action="/search/">
    {% csrf_token %}
     <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="searchTerm">
     <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
   </form>
 </div>
</nav>
   {% block content %}
   {% endblock %}

   <!-- Optional JavaScript -->
   <!-- jQuery first, then Popper.js, then Bootstrap JS -->
   <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
 </body>
</html>

main/templates/main/details.html
{% extends 'main/base.html' %}
{% block content %}

<div class="container">
  <br>
  <div class="card">
    <div class="card-body">
      <div class="row">
        <div class="col-md-4">
          <img class="card-img-top" src="https://image.tmdb.org/t/p/w300{{ response.poster_path }}" alt="Card image cap" width= "75%">

        </div>
        <div class="col-md-8">
          <h3 class="text-centre">{{ response.title }}</h3>
          <p>{{ response.overview }}</p>
          <h5>Rating : {{ response.vote_average }}</h5>
        </div>

      </div>
    </div>
  </div>

</div>
<br>
<div class="card">
  <div class="card-body">
    <h3 class="text-center">Post your Review!</h3>
    <form  action= "{% url 'main:review'  %}" method="post">
      {% csrf_token %}
      <input type = "hidden" name = "movieid" value = "{{ response.id }}" />

      <label for="review">Review</label>
      <textarea name="review" rows="5" cols="30" class="form-control"></textarea>
      <label for="rating">Rating</label>
      <input type="text" name="rating" class="form-control">
      <br>
      <input type="submit" name="" value="Add Review" class="btn btn-danger">
    </form>

  </div>

</div>

<div class="card">
  <div class="card-body">
    {% for reviews in review %}
    <div class="card" style="background-color: #FFE5B4">
      <div class="card-body">
        <div class="row">
          <div class="col-md-3">
            <h5 class="text-left">{{ reviews.user }}</h5>
            <h5 >{{ reviews.rating }}</h5>

          </div>
          <div class="col-md-9">
            <p>{{ reviews.review }}</p>

          </div>

        </div>

      </div>

    </div>
    {% endfor %}


  </div>

</div>
{% endblock %}

main/templates/main/genre.html
<!-- #django way of templating is this. create a main folder within the tenplates folder within the main folder -->
{% extends 'main/base.html' %}
{% block content %}

<div class="container">
 <br>
 <div class="topic" style="
   /* border: 2px solid white; */
   display: flex;
   height: 34vh;
   /* text-align: center; */
   align-items: center;
   margin-bottom: 7px;
   color: antiquewhite;
   /* background-position: center; */
   justify-content: center;
   font-family: fantasy;
   font-size: 10vw;
">F I L M S T E R</div>
 <div class="top" style="
 height: 0vh;
 margin-bottom: 7px;
 background-position: center;
 /* width: 70em; */
 margin-left: 15px;
 border-radius: 11px;
 margin-right: 18px;
"></div>
 <div class="card" id="backdrop" style="background: transparent; border:none;" >
   <div class="card-body">
     <div class="row">
      {% for key, value in response3.items %}
       <div class="col-md-4">
         <div class="card" style="margin-bottom: 1em;">
           <div class="card-body">
               <img class="card-img-top" style="height:25em;" src="https://image.tmdb.org/t/p/w300{{ value.poster_path }}" alt="Card image cap" width= "75%">
               <br><br>
               <h5 class="card-title">{{ value.title }}</h5>
               <i>{{ value.release_date }}</i>
               <br><br>
               <div class="text-centre">
                 <a href="/details/{{ key }}/" class="btn btn-sm btn-info aria-pressed="true" " action="/detail/">Reviews and More</a>
               </div>
           </div>
         </div>

       </div>
       {% endfor %}

     </div>
   </div>
   <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->

 </div>
</div>

{% endblock %}
<!-- <li><a href="{% url 'main:details' movie.id %}">{{ movie.name }} -Directed by {{movie.director}}</li> -->
  <!-- #url routing we specified app_name as main in our urls.py and then we set our url route of detail page we had given the name details to that page and we passed it here along with the movie id parameter -->

main/templates/main/index.html
<!-- #django way of templating is this. create a main folder within the tenplates folder within the main folder -->
{% extends 'main/base.html' %}
{% block content %}

<div class="container">
 <br>
 <div class="topic" style="
   /* border: 2px solid white; */
   display: flex;
   height: 34vh;
   /* text-align: center; */
   align-items: center;
   /* background-image: url(https://miro.medium.com/max/875/1*S5XhemJtXYa6s_JfuEV10Q.gif); */
   background-size: cover;
   margin-bottom: 7px;
   color: antiquewhite;
   /* background-position: center; */
   justify-content: center;
   font-family: fantasy;
   font-size: 10vw;
">F I L M S T E R</div>
 <div class="top" style="
 height: 65vh;
 background-image: url(https://miro.medium.com/max/875/1*S5XhemJtXYa6s_JfuEV10Q.gif);
 background-size: cover;
 margin-bottom: 7px;
 background-position: center;
 /* width: 70em; */
 margin-left: 15px;
 border-radius: 11px;
 margin-right: 18px;
"></div>
 <div class="card" id="backdrop" style="background: transparent; border:none;" >
   <div class="card-body">
     <div class="row">
       {% for movie in movies %}
       <div class="col-md-4">
         <div class="card" style="margin-bottom: 1em;">
           <div class="card-body">
               <img class="card-img-top" style="height:25em;" src="{{ movie.image }}" alt="Card image cap" width= "75%">
               <br><br>
               <h5 class="card-title">{{ movie.name }}</h5>
               <i>{{ movie.release_date }}</i>
               <br><br>
               <div class="text-centre">
                 <a href="{% url 'main:detail' movie.id %}" class="btn btn-sm btn-info aria-pressed="true" ">Reviews and More</a>
               </div>
           </div>
         </div>

       </div>
       {% endfor %}

     </div>
   </div>
   <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->

 </div>
</div>

{% endblock %}
<!-- <li><a href="{% url 'main:details' movie.id %}">{{ movie.name }} -Directed by {{movie.director}}</li> -->
  <!-- #url routing we specified app_name as main in our urls.py and then we set our url route of detail page we had given the name details to that page and we passed it here along with the movie id parameter -->

main/templates/main/search.html
<!-- #django way of templating is this. create a main folder within the tenplates folder within the main folder -->
{% extends 'main/base.html' %}
{% block content %}

<div class="container">
 <br>
 <div class="topic" style="
   /* border: 2px solid white; */
   display: flex;
   height: 34vh;
   /* text-align: center; */
   align-items: center;
   margin-bottom: 7px;
   color: antiquewhite;
   /* background-position: center; */
   justify-content: center;
   font-family: fantasy;
   font-size: 10vw;
">F I L M S T E R</div>
 <div class="top" style="
 height: 0vh;
 margin-bottom: 7px;
 background-position: center;
 /* width: 70em; */
 margin-left: 15px;
 border-radius: 11px;
 margin-right: 18px;
"></div>
<h3 class="text-center" style="color:white">Search Results for '{{ searchTerm }}'</h3>
 <div class="card" id="backdrop" style="background: transparent; border:none;" >
   <div class="card-body">
     <div class="row">
      {% for key, value in response3.items %}
       <div class="col-md-4">
         <div class="card" style="margin-bottom: 1em;">
           <div class="card-body">
               <img class="card-img-top" style="height:25em;" src="https://image.tmdb.org/t/p/w300{{ value.poster_path }}" alt="Card image cap" width= "75%">
               <br><br>
               <h5 class="card-title">{{ value.title }}</h5>
               <i>{{ value.release_date }}</i>
               <br><br>
               <div class="text-centre">
                 <a href="/details/{{ key }}/" class="btn btn-sm btn-info aria-pressed="true" " action="/detail/">Reviews and More</a>
               </div>
           </div>
         </div>

       </div>
       {% endfor %}

     </div>
   </div>
   <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->

 </div>
</div>

{% endblock %}
<!-- <li><a href="{% url 'main:details' movie.id %}">{{ movie.name }} -Directed by {{movie.director}}</li> -->
  <!-- #url routing we specified app_name as main in our urls.py and then we set our url route of detail page we had given the name details to that page and we passed it here along with the movie id parameter -->